export const defaultGame = {
	backgroundLoopTime: 30,
	backgroundSpeed: 1,
	score: 0,
	rescues: 0,
	losses: 0,
	maxLives: 3,
	sounds: {
		menu: {
			path: "menu.mp3",
			volume: 0.4,
			loop: true,
		},
		click: {
			path: "click.mp3",
			volume: 0.5,
		},
		theme: {
			path: "theme.mp3",
			volume: 0.1,
			loop: true,
		},
		hit: {
			path: "hit.mp3",
			volume: 0.5,
		},
		gameOver: {
			path: "game-over.mp3",
			volume: 0.5,
		},
	},
	player: {
		maxTop: 470,
		minTop: 3,
		maxLeft: 848,
		minLeft: -35,
		initialSpeed: 6,
		maxSpeed: 6,
		attackMarginLeft: 110,
		attackMarginTop: 12,
		attackSpeed: 15,
		maxAttackLeft: 900,
		respawnDelay: 1000,
		canAttack: true,
		attackDuration: 200,
		KEYS: {
			KeyW: { action: "moveUp", pressed: false },
			KeyS: { action: "moveDown", pressed: false },
			KeyD: { action: "moveRight", pressed: false },
			KeyA: { action: "moveLeft", pressed: false },
			Space: { action: "attack", pressed: false },
		},
		sounds: {
			attack: {
				path: "player/attack.mp3",
				volume: 0.3,
			},
		},
		classes: {
			main: "player",
			attack: "player-attack-animation",
			walk: "player-walk-animation",
			fly: "player-fly-animation",
			death: "player-death-animation",
			idle: "player-idle-animation",
		},
	},
	enemy1: {
		initialSpeed: 3,
		maxSpeed: 40,
		minLeft: 3,
		maxLeft: 895,
		maxTop: 334,
		minTop: 3,
		acceleration: 1.02,
		respawnDelay: 1000,
		prize: 30,
		fall: true,
		canAttack: true,
		attackDuration: 1000,
		attackSpeed: 3,
		attackMarginTop: 12,
		maxAttackTop: 500,
		sounds: {
			death: {
				path: "enemy-1/death.mp3",
				volume: 0.3,
			},
			talk: {
				path: "enemy-1/talk.mp3",
				volume: 0.3,
			},
			attack: {
				path: "enemy-1/attack.mp3",
				volume: 0.7,
			},
			explosion: {
				path: "enemy-1/explosion.mp3",
				volume: 0.3,
			},
		},
		classes: {
			main: "enemy-1",
			attack: "enemy-1-attack-animation",
			fly: "enemy-1-fly-animation",
			death: "enemy-1-death-animation",
		},
	},
	enemy2: {
		initialSpeed: 1.5,
		maxSpeed: 30,
		minLeft: 3,
		maxLeft: 830,
		respawnDelay: 5000,
		acceleration: 1.1,
		prize: 10,
		attackDuration: 1000,
		sounds: {
			death: {
				path: "enemy-2/death.mp3",
				volume: 0.3,
			},
			talk: {
				path: "enemy-2/talk.mp3",
				volume: 0.3,
			},
		},
		classes: {
			main: "enemy-2",
			attack: "enemy-2-attack-animation",
			walk: "enemy-2-walk-animation",
			death: "enemy-2-death-animation",
		},
	},
	friend: {
		initialSpeed: 0.5,
		maxSpeed: 1,
		acceleration: 1.05,
		maxLeft: 906,
		minLeft: 0,
		respawnDelay: 6000,
		prize: 50,
		penalty: 10,
		sounds: {
			death: {
				path: "friend/death.mp3",
				volume: 0.2,
			},
			talk: {
				path: "friend/talk.mp3",
				volume: 0.2,
			},
		},
		classes: {
			main: "friend",
			walk: "friend-walk-animation",
			death: "friend-death-animation",
		},
	},
};
